### ISSUE TITLE
Can I use XYPlot?

### ISSUE THREAD

**Issue by za-wa-n-go** [s1dlx/comfy_meh#2]
Can we use XYplot in the form of a supermerger to see the difference due to merge weights?

**Comment by s1dlx** [comment]
I don't see why not, have you tried yet?

**Comment by za-wa-n-go** [comment]
I am embarrassed to say that doing XYPlot with ComfyUI is difficult and I don't know how to try it......

**Comment by s1dlx** [comment]
You can try something like this
https://github.com/hnmr293/ComfyUI-nodes-hnmr

or 
https://civitai.com/models/31126/imagesgrid-comfy-plugin-xy-plot

**Comment by za-wa-n-go** [comment]
thankyou!
It looks like I can do it!
But when I brought ComfyUI up to date, I get the following Traceback and can't load the meh node.

Traceback (most recent call last):
  File "C:\Product\ComfyUI\nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Product\ComfyUI\custom_nodes\comfy_meh\__init__.py", line 1, in <module>
    from .meh import NODE_CLASS_MAPPINGS
  File "C:\Product\ComfyUI\custom_nodes\comfy_meh\meh.py", line 7, in <module>
    from comfy.sd import CLIP, VAE, ModelPatcher, calculate_parameters, load_model_weights
ImportError: cannot import name 'calculate_parameters' from 'comfy.sd' (C:\Product\ComfyUI\comfy\sd.py)

Cannot import C:\Product\ComfyUI\custom_nodes\comfy_meh module for custom nodes: cannot import name 'calculate_parameters' from 'comfy.sd' (C:\Product\ComfyUI\comfy\sd.py)

**Comment by alexbofa** [comment]
> thankyou! It looks like I can do it! But when I brought ComfyUI up to date, I get the following Traceback and can't load the meh node.
> 
> Traceback (most recent call last): File "C:\Product\ComfyUI\nodes.py", line 1693, in load_custom_node module_spec.loader.exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "C:\Product\ComfyUI\custom_nodes\comfy_meh__init__.py", line 1, in from .meh import NODE_CLASS_MAPPINGS File "C:\Product\ComfyUI\custom_nodes\comfy_meh\meh.py", line 7, in from comfy.sd import CLIP, VAE, ModelPatcher, calculate_parameters, load_model_weights ImportError: cannot import name 'calculate_parameters' from 'comfy.sd' (C:\Product\ComfyUI\comfy\sd.py)
> 
> Cannot import C:\Product\ComfyUI\custom_nodes\comfy_meh module for custom nodes: cannot import name 'calculate_parameters' from 'comfy.sd' (C:\Product\ComfyUI\comfy\sd.py)

update **comfy_meh**

**Comment by s1dlx** [comment]
Thank you @alexbofa !

**Comment by za-wa-n-go** [comment]
Thank you for your response!

I have just updated ComfyUI to the latest version, but the ModelPatcher seems to have been moved after the above action, and the same error is occurring again.
It seems that it is now independent as model_patcher.py instead of in sd.py.

Traceback (most recent call last):
  File "C:\Product\ComfyUI\nodes.py", line 1694, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Product\ComfyUI\custom_nodes\comfy_meh\__init__.py", line 1, in <module>
    from .meh import NODE_CLASS_MAPPINGS
  File "C:\Product\ComfyUI\custom_nodes\comfy_meh\meh.py", line 7, in <module>
    from comfy.sd import CLIP, VAE, ModelPatcher, load_model_weights
ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (C:\Product\ComfyUI\comfy\sd.py)

Cannot import C:\Product\ComfyUI\custom_nodes\comfy_meh module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (C:\Product\ComfyUI\comfy\sd.py)
